services:
  postgres:
    image: postgres:16
    container_name: bookstore-postgres

    environment:
      POSTGRES_DB: bookstore
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5433:5432"

  redis:
    image: redis:7
    container_name: bookstore-redis

    ports:
      - "6379:6379"